### ISSUE TITLE
Allow to configure a custom key prefix

### ISSUE THREAD

**Issue by lukas1984** [mprops/mprops-java#2]
It would be nice if the key prefix can be configured and can be of arbitrary length.

My scenario is: I'm using this lib to store some SQL queries that are too long to fit on a single row (and it's just great that I don't need to use those silly backslashes!). I would like to use the double hyphen "--" to mark the keys, so that they are recognized as comments and the entire file looks as valid SQL on my IDE.

Thanks in advance

**Comment by mfursov** [comment]
Intellij IDEA plugin update is needed to make this patch complete.

This requirement makes the fix not trivial, so I can't share any plans on time when this feature can be fully implemented (both plugin & Java library).

Without the plugin support the fix is trivial. I will add it this week.

**Comment by mfursov** [comment]
Should be fixed as a part of https://github.com/mprops/mprops-java/commit/d9f05a8f125c40a700a50d6a677433827aec81bf
